[package]
name = "hsk"
version = "1.0.0"
authors = ["Preston Wang-Stosur-Bassett <p.wanstobas@gmail.com>"]
description = "Authoritative, versioned HSK and Chinese proficiency classifications"
repository = "https://github.com/sotch-pr35mac/hsk"
readme = "README.md"
keywords = ["chinese", "hanzi", "hsk"]
categories = ["text-processing"]
license = "MIT"
edition = "2024"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "0.1.24"

[build-dependencies]
unicode-normalization = "0.1.24"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "lookup"
harness = false
